Gemspec/OrderedDependencies:
  Enabled: false

Layout/AlignHash:
  Enabled: true
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
